<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Académico</title>
    <link rel="stylesheet" href="estilos.css">
</head>
<body>

    <div class="contenedor">

        <h1>Sistema Académico</h1>

        <a href="estudiantes.php" class="boton">
            Gestión de Estudiantes
        </a>

        <a href="profesores.php" class="boton">
            Gestión de Profesores
        </a>

        <a href="nomina.php" class="boton">
            Gestión de Nómina
        </a>

    </div>

</body>
</html>